# Scraping Intro Homework: Wikipedia Table

In this assignment, we'll be extracting data from Wikipedia's table of the tallest buildings in Brooklyn: https://en.wikipedia.org/wiki/List_of_tallest_buildings_in_Brooklyn

### 0) Setup

Import `requests`, `BeautifulSoup`, and `pandas`. Although this homework uses `BeautifulSoup`, you can choose to use `lxml` instead, if you prefer.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

### 1) Grab the HTML for the webpage linked above

Use `requests` to get the HTML, assigning it to a variable

In [4]:
url = requests.get('https://en.wikipedia.org/wiki/List_of_tallest_buildings_in_Brooklyn')
html = url.text

### 2) Convert the HTML into a `BeautifulSoup` object

In [6]:
soup = BeautifulSoup(html)
soup

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-enabled vector-feature-main-menu-pinned-disabled vector-feature-limited-width-enabled vector-feature-limited-width-content-enabled vector-feature-zebra-design-disabled" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of tallest buildings in Brooklyn - Wikipedia</title>
<script>document.documentElement.className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-enabled vector-feature-main-menu-pinned-disabled vector-feature-limited-width-enabled vector-feature-limited-width-content-enabled vector-feature-zebra-design-disabled";(function(){var cookie=document.cookie.match(/(?:^|; )enwikimwclientprefs=([^;]+)/);if(cookie){var featureName=cookie[1];document.documentElement.className=document.documentElement.className.replace(featureName+'-enabled',featureName+'-disabled');}}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"22580641-c492-46a8-9283-ea485a77e177","wgCSPNonce":false,
"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_tallest_buildings_in_Brooklyn","wgTitle":"List of tallest buildings in Brooklyn","wgCurRevisionId":1160732736,"wgRevisionId":1160732736,"wgArticleId":44497653,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 errors: missing periodical","All articles with dead external links","Articles with dead external links from September 2017","Articles with permanently dead external links","Articles with short description","Short description is different from Wikidata","Use mdy dates from January 2021","Use American English from January 2021","All Wikipedia articles written in American English","Commons category link is on Wikidata","Featured lists","Lists of tallest buildings in New York (state)","Lists of tallest buildings in the United States by city","Brooklyn-related lists","Skyscrapers in Brooklyn",
"Lists of buildings and structures in New York City"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_tallest_buildings_in_Brooklyn","wgRelevantArticleId":44497653,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":100000,"wgNoticeProject":"wikipedia","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":10,"wgULSCurrentAutonym":"English","wgEditSubmitButtonLabelPublish":true,"wgCentralAuthMobileDomain":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":true,"wgULSisLanguageSelectorEmpty":false,
"wgWikibaseItemId":"Q20717285","GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"skins.vector.user.styles":"ready","ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","skins.vector.user":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","codex-search-styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.wikimediaBadges":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","mmv.head","mmv.bootstrap.autostart",
"ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.cx.eventlogging.campaigns","ext.quicksurveys.init","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.charinsert","ext.gadget.extra-toolbar-buttons","ext.gadget.switcher","ext.centralauth.centralautologin","ext.popups","ext.echo.centralauth","ext.uls.compactlinks","ext.uls.interface","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.implement("user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});});});</script>
<link href="/w/load.php?lang=en&amp;modules=codex-search-styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.41.0-wmf.13" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-crossorigin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/1200px-The_Brooklyn_Tower_010.jpg" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="1600" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/800px-The_Brooklyn_Tower_010.jpg" property="og:image"/>
<meta content="800" property="og:image:width"/>
<meta content="1067" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/640px-The_Brooklyn_Tower_010.jpg" property="og:image"/>
<meta content="640" property="og:image:width"/>
<meta content="853" property="og:image:height"/>
<meta content="width=1000" name="viewport"/>
<meta content="List of tallest buildings in Brooklyn - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/List_of_tallest_buildings_in_Brooklyn" media="only screen and (max-width: 720px)" rel="alternate"/>
<link href="/w/index.php?title=List_of_tallest_buildings_in_Brooklyn&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/opensearch_desc.php" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_tallest_buildings_in_Brooklyn" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="//login.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_tallest_buildings_in_Brooklyn rootpage-List_of_tallest_buildings_in_Brooklyn skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark" role="navigation">
<div class="vector-menu vector-dropdown vector-menu-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown">
<input aria-haspopup="true" aria-label="Main menu" class="vector-menu-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-menu-heading cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
<span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-menu-heading-label">Main menu</span>
</label>
<div class="vector-menu-content vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list"><li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li><li class="mw-list-item" id="n-sitesupport"><a href="https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_en.wikipedia.org&amp;uselang=en" title="Support us by donating to the Wikimedia Foundation"><span>Donate</span></a></li></ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list"><li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li></ul>
</div>
</div>
<div class="vector-main-menu-action vector-main-menu-action-lang-alert">
<div class="vector-main-menu-action-item">
<div class="vector-main-menu-action-heading vector-menu-heading">Languages</div>
<div class="vector-main-menu-action-content vector-menu-content">
<div class="mw-message-box-notice vector-language-sidebar-alert mw-message-box">Language links are at the top of the page across from the title.</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" id="" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links" role="navigation">
<div class="vector-menu mw-portlet mw-portlet-vector-user-menu-overflow" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list"><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount-2"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+tallest+buildings+in+Brooklyn" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login-2"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+tallest+buildings+in+Brooklyn" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a></li></ul>
</div>
</div>
<div class="vector-menu vector-dropdown vector-menu-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-menu-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-menu-heading cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label">
<span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-menu-heading-label">Personal tools</span>
</label>
<div class="vector-menu-content vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list"><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+tallest+buildings+in+Brooklyn" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+tallest+buildings+in+Brooklyn" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li></ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">
		Pages for logged out editors <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>
</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list"><li class="mw-list-item" id="pt-anoncontribs"><a accesskey="y" href="/wiki/Special:MyContributions" title="A list of edits made from this IP address [y]"><span>Contributions</span></a></li><li class="mw-list-item" id="pt-anontalk"><a accesskey="n" href="/wiki/Special:MyTalk" title="Discussion about edits from this IP address [n]"><span>Talk</span></a></li></ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-main-menu-container">
<div id="mw-navigation">
<nav aria-label="Site" class="vector-main-menu-landmark" id="mw-panel" role="navigation">
<div class="vector-pinned-container" id="vector-main-menu-pinned-container">
</div>
</nav>
</div>
</div>
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>
</div>
<input class="vector-menu-checkbox" id="vector-toc-collapsed-checkbox" type="checkbox"/>
<nav aria-label="Contents" class="mw-table-of-contents-container vector-toc-landmark vector-sticky-pinned-container" data-event-name="ui.sidebar-toc" id="mw-panel-toc" role="navigation">
<div class="vector-pinned-container" id="vector-toc-pinned-container">
<div class="vector-toc vector-pinnable-element" id="vector-toc">
<div class="vector-pinnable-header vector-toc-pinnable-header vector-pinnable-header-pinned" data-feature-name="toc-pinned" data-pinnable-element-id="vector-toc">
<h2 class="vector-pinnable-header-label">Contents</h2>

### 3) Use `.select(...)` (and `[0]`) to select the main table

That's the one directly under the "Tallest buildings" heading.

Print out the first 100 characters of text from the table to make sure you have the right one.

In [20]:
table = soup.select('table tr')
table

[<tr>
 <th>Rank
 </th>
 <th>Name<sup class="reference" id="ref_id1none"><a href="#endnote_id1none">[a]</a></sup>
 </th>
 <th class="unsortable">Image
 </th>
 <th data-sort-type="number">Height<br/><span style="font-size:85%;">ft (m)</span>
 </th>
 <th>Floors
 </th>
 <th>Year completed
 </th>
 <th class="unsortable">Notes
 </th></tr>,
 <tr>
 <td style="word-spacing: -5px;">1
 </td>
 <td><a href="/wiki/The_Brooklyn_Tower" title="The Brooklyn Tower">The Brooklyn Tower</a>
 </td>
 <td><a class="image" href="/wiki/File:The_Brooklyn_Tower_010.jpg" title="City Point"><img alt="A view of The Brooklyn Tower looking north from Bond Street" data-file-height="2048" data-file-width="1536" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/80px-The_Brooklyn_Tower_010.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/120px-The_Brooklyn_Tower_010.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/160px-The_Brooklyn_Tower_010.jpg 2x" width="80"/></a>
 </td>
 <td>1,073 (327)
 </td>
 <td>93
 </td>
 <td>2022
 </td>
 <td align="left">Topped out in October 2021.<sup class="reference" id="cite_ref-9De_2-1"><a href="#cite_note-9De-2">[2]</a></sup><sup class="reference" id="cite_ref-RealDealJDS_22-1"><a href="#cite_note-RealDealJDS-22">[22]</a></sup><sup class="reference" id="cite_ref-20151109newyorkyimby_23-0"><a href="#cite_note-20151109newyorkyimby-23">[23]</a></sup><sup class="reference" id="cite_ref-archive201703300842_24-0"><a href="#cite_note-archive201703300842-24">[24]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">2
 </td>
 <td><a href="/wiki/City_Point_(Brooklyn)" title="City Point (Brooklyn)">Brooklyn Point</a>
 </td>
 <td><a class="image" href="/wiki/File:BrooklynPointII.jpg" title="City Point"><img alt="A view of City Point looking west from Flatbush Avenue" data-file-height="4032" data-file-width="3024" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a0/BrooklynPointII.jpg/80px-BrooklynPointII.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a0/BrooklynPointII.jpg/120px-BrooklynPointII.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a0/BrooklynPointII.jpg/160px-BrooklynPointII.jpg 2x" width="80"/></a>
 </td>
 <td>720 (219)
 </td>
 <td>68
 </td>
 <td>2019
 </td>
 <td align="left">The final phase of <a href="/wiki/Extell_Development_Company" title="Extell Development Company">Extell's</a> City Point development; topped out in April 2019, it is now the second tallest building in Brooklyn.<sup class="reference" id="cite_ref-NewYorkYimby.com_25-0"><a href="#cite_note-NewYorkYimby.com-25">[25]</a></sup> Also known as 138 Willoughby Street,<sup class="reference" id="cite_ref-20160122yimbynews_26-0"><a href="#cite_note-20160122yimbynews-26">[26]</a></sup><sup class="reference" id="cite_ref-27"><a href="#cite_note-27">[27]</a></sup> 1 City Point,<sup class="reference" id="cite_ref-BP_city_realty_28-0"><a href="#cite_note-BP_city_realty-28">[28]</a></sup> and City Point Tower III.<sup class="reference" id="cite_ref-BP_city_realty_28-1"><a href="#cite_note-BP_city_realty-28">[28]</a></sup><sup class="reference" id="cite_ref-Brooklyn_Point_1_29-0"><a href="#cite_note-Brooklyn_Point_1-29">[29]</a></sup><sup class="reference" id="cite_ref-FAA_1_30-0"><a href="#cite_note-FAA_1-30">[30]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">3
 </td>
 <td><a href="/wiki/11_Hoyt" title="11 Hoyt">11 Hoyt</a>
 </td>
 <td><a class="image" href="/wiki/File:11HoytMay27.jpg" title="11 Hoyt Street"><img alt="11 Hoyt Street" data-file-height="1632" data-file-width="918" decoding="async" height="142" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/39/11HoytMay27.jpg/80px-11HoytMay27.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/39/11HoytMay27.jpg/120px-11HoytMay27.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/39/11HoytMay27.jpg/160px-11HoytMay27.jpg 2x" width="80"/></a>
 </td>
 <td>626 (191)
 </td>
 <td>51
 </td>
 <td>2020
 </td>
 <td align="left">Topped out in June 2019.<sup class="reference" id="cite_ref-20190604curbed-18651997_31-0"><a href="#cite_note-20190604curbed-18651997-31">[31]</a></sup> A redevelopment of Macy's former footprint in Downtown Brooklyn, with a design seemingly inspired by <a href="/wiki/8_Spruce_Street" title="8 Spruce Street">8 Spruce Street</a>.<sup class="reference" id="cite_ref-20180410newyorkyimby_32-0"><a href="#cite_note-20180410newyorkyimby-32">[32]</a></sup><sup class="reference" id="cite_ref-Studio_Gang_1_33-0"><a href="#cite_note-Studio_Gang_1-33">[33]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">4
 </td>
 <td><a href="/wiki/The_Hub_(building)" title="The Hub (building)">The Hub</a>
 </td>
 <td><a class="image" href="/wiki/File:333_Schermerhorn_Street_viewed_from_Flatbush_Ave,_Sept_2017.jpg" title="The Hub"><img alt="A view of The Hub looking west from Flatbush Avenue" data-file-height="1852" data-file-width="1198" decoding="async" height="124" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/21/333_Schermerhorn_Street_viewed_from_Flatbush_Ave%2C_Sept_2017.jpg/80px-333_Schermerhorn_Street_viewed_from_Flatbush_Ave%2C_Sept_2017.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/21/333_Schermerhorn_Street_viewed_from_Flatbush_Ave%2C_Sept_2017.jpg/120px-333_Schermerhorn_Street_viewed_from_Flatbush_Ave%2C_Sept_2017.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/21/333_Schermerhorn_Street_viewed_from_Flatbush_Ave%2C_Sept_2017.jpg/160px-333_Schermerhorn_Street_viewed_from_Flatbush_Ave%2C_Sept_2017.jpg 2x" width="80"/></a>
 </td>
 <td>611 (186)
 </td>
 <td>52
 </td>
 <td>2017
 </td>
 <td align="left">Also known as 333 Schermerhorn Street. Topped out on December 16, 2015.<sup class="reference" id="cite_ref-Emporis1216010_34-0"><a href="#cite_note-Emporis1216010-34">[34]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter14016_35-0"><a href="#cite_note-SkyscraperCenter14016-35">[35]</a></sup><sup class="reference" id="cite_ref-archive201601082253_36-0"><a href="#cite_note-archive201601082253-36">[36]</a></sup><sup class="reference" id="cite_ref-37"><a href="#cite_note-37">[37]</a></sup><sup class="reference" id="cite_ref-Dattner_Architects_1_38-0"><a href="#cite_note-Dattner_Architects_1-38">[38]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">5
 </td>
 <td><a href="/wiki/AVA_DoBro" title="AVA DoBro">AVA DoBro</a>
 </td>
 <td><a class="image" href="/wiki/File:AVADobro1.jpg" title="Avalon Willoughby West"><img alt="Avalon Willoughby West, a high-rise clad in blue glass, photographed during its construction" data-file-height="1632" data-file-width="918" decoding="async" height="142" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/AVADobro1.jpg/80px-AVADobro1.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/AVADobro1.jpg/120px-AVADobro1.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/3a/AVADobro1.jpg/160px-AVADobro1.jpg 2x" width="80"/></a>
 </td>
 <td>596 (182)
 </td>
 <td>58
 </td>
 <td>2015
 </td>
 <td align="left">Also known as 100 Willoughby Street, Avalon Willoughby Square, and 214 Duffield Street.<sup class="reference" id="cite_ref-NYDN1_39-0"><a href="#cite_note-NYDN1-39">[39]</a></sup><sup class="reference" id="cite_ref-Emporis1172388_40-0"><a href="#cite_note-Emporis1172388-40">[40]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter9815_41-0"><a href="#cite_note-SkyscraperCenter9815-41">[41]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">6
 </td>
 <td><a href="/wiki/388_Bridge_Street" title="388 Bridge Street">388 Bridge Street</a>
 </td>
 <td><a class="image" href="/wiki/File:388_Bridge_Street,_Brooklyn,_Sept_2017.jpg" title="388 Bridge Street"><img alt="A street view of 388 Bridge Street" data-file-height="2097" data-file-width="1965" decoding="async" height="85" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/90/388_Bridge_Street%2C_Brooklyn%2C_Sept_2017.jpg/80px-388_Bridge_Street%2C_Brooklyn%2C_Sept_2017.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/90/388_Bridge_Street%2C_Brooklyn%2C_Sept_2017.jpg/120px-388_Bridge_Street%2C_Brooklyn%2C_Sept_2017.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/90/388_Bridge_Street%2C_Brooklyn%2C_Sept_2017.jpg/160px-388_Bridge_Street%2C_Brooklyn%2C_Sept_2017.jpg 2x" width="80"/></a>
 </td>
 <td>590 (180)
 </td>
 <td>51
 </td>
 <td>2014
 </td>
 <td align="left"><sup class="reference" id="cite_ref-NYDN1_39-1"><a href="#cite_note-NYDN1-39">[39]</a></sup><sup class="reference" id="cite_ref-Emporis325334_42-0"><a href="#cite_note-Emporis325334-42">[42]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter3266_43-0"><a href="#cite_note-SkyscraperCenter3266-43">[43]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">7
 </td>
 <td>590 Fulton Street
 </td>
 <td><a class="image" href="/wiki/File:250_Ashland_Place.jpg" title="250 Ashland Place"><img alt="250 Ashland Place" data-file-height="1632" data-file-width="918" decoding="async" height="142" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a7/250_Ashland_Place.jpg/80px-250_Ashland_Place.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a7/250_Ashland_Place.jpg/120px-250_Ashland_Place.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a7/250_Ashland_Place.jpg/160px-250_Ashland_Place.jpg 2x" width="80"/></a>
 </td>
 <td>568 (173)
 </td>
 <td>52
 </td>
 <td>2016
 </td>
 <td align="left">Also known as 250 Ashland Place and Gotham BAM Tower<sup class="reference" id="cite_ref-Emporis1218704_44-0"><a href="#cite_note-Emporis1218704-44">[44]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter17698_45-0"><a href="#cite_note-SkyscraperCenter17698-45">[45]</a></sup><sup class="reference" id="cite_ref-FAA_2_46-0"><a href="#cite_note-FAA_2-46">[46]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">8
 </td>
 <td>18 Sixth Avenue
 </td>
 <td>—
 </td>
 <td>532 (162)
 </td>
 <td>49
 </td>
 <td>2022
 </td>
 <td align="left">Also known as the Pacific Park B4 Tower.<sup class="reference" id="cite_ref-47"><a href="#cite_note-47">[47]</a></sup><sup class="reference" id="cite_ref-48"><a href="#cite_note-48">[48]</a></sup><sup class="reference" id="cite_ref-20180927newyorkyimby_49-0"><a href="#cite_note-20180927newyorkyimby-49">[49]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">9
 </td>
 <td><a href="/wiki/City_Point_(Brooklyn)" title="City Point (Brooklyn)">City Tower</a>
 </td>
 <td><a class="image" href="/wiki/File:City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg" title="City Point Tower II"><img alt="City Point Tower II, a high-rise clad in light-toned stone and dark-toned glass in irregular patterns, viewed from street level" data-file-height="3264" data-file-width="2448" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a2/City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg/80px-City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a2/City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg/120px-City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a2/City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg/160px-City_Point_Tower_II_Brooklyn_NY_2015_06_10_03.jpg 2x" width="80"/></a>
 </td>
 <td>515 (157)
 </td>
 <td>46
 </td>
 <td>2016
 </td>
 <td align="left">Also known as City Point Tower II,<sup class="reference" id="cite_ref-SkyscraperCenter15744_50-0"><a href="#cite_note-SkyscraperCenter15744-50">[50]</a></sup> 10 City Point, and 336 Flatbush Avenue Extension<sup class="reference" id="cite_ref-51"><a href="#cite_note-51">[51]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">10
 </td>
 <td><a href="/wiki/Brooklyner" title="Brooklyner">The Brooklyner</a>
 </td>
 <td><a class="image" href="/wiki/File:Brooklyner_Gallatin_Fulton_jeh.jpg" title="The Brooklyner"><img alt="A view of The Brooklyner's side elevation from street level" data-file-height="3143" data-file-width="1634" decoding="async" height="154" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Brooklyner_Gallatin_Fulton_jeh.jpg/80px-Brooklyner_Gallatin_Fulton_jeh.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Brooklyner_Gallatin_Fulton_jeh.jpg/120px-Brooklyner_Gallatin_Fulton_jeh.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Brooklyner_Gallatin_Fulton_jeh.jpg/160px-Brooklyner_Gallatin_Fulton_jeh.jpg 2x" width="80"/></a>
 </td>
 <td>514 (157)
 </td>
 <td>51
 </td>
 <td>2010
 </td>
 <td align="left">Tallest high-rise building in Brooklyn between 2009 and 2013.<sup class="reference" id="cite_ref-NYDN3_3-2"><a href="#cite_note-NYDN3-3">[3]</a></sup><sup class="reference" id="cite_ref-NYDN2_4-1"><a href="#cite_note-NYDN2-4">[4]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter3557_52-0"><a href="#cite_note-SkyscraperCenter3557-52">[52]</a></sup><sup class="reference" id="cite_ref-Emporis324243_53-0"><a href="#cite_note-Emporis324243-53">[53]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">11
 </td>
 <td><a href="/wiki/Williamsburgh_Savings_Bank_Tower" title="Williamsburgh Savings Bank Tower">Williamsburgh Savings Bank Tower</a>
 </td>
 <td><a class="image" href="/wiki/File:Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg" title="Williamsburgh Savings Bank Tower"><img alt="Williamsburgh Savings Bank Tower, a limestone art-deco high-rise building, viewed from street level" data-file-height="2775" data-file-width="2337" decoding="async" height="95" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg/80px-Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg/120px-Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/73/Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg/160px-Williamsburgh_Savings_Bank_Tower_from_Hanson_Place_closer.jpg 2x" width="80"/></a>
 </td>
 <td>512 (156)
 </td>
 <td>42
 </td>
 <td>1929
 </td>
 <td align="left">Tallest high-rise building in Brooklyn between 1929 and 2009. Also known as One Hanson Place.<sup class="reference" id="cite_ref-Emporis113805_5-2"><a href="#cite_note-Emporis113805-5">[5]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter3598_54-0"><a href="#cite_note-SkyscraperCenter3598-54">[54]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">12
 </td>
 <td>540 Fulton Street
 </td>
 <td><a class="image" href="/wiki/File:540FultonII.jpg" title="540 Fulton Street"><img alt="540 Fulton Street" data-file-height="4032" data-file-width="3024" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/540FultonII.jpg/80px-540FultonII.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/540FultonII.jpg/120px-540FultonII.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9a/540FultonII.jpg/160px-540FultonII.jpg 2x" width="80"/></a>
 </td>
 <td>511 (156)
 </td>
 <td>43
 </td>
 <td>2020
 </td>
 <td align="left">Topped out in 2019.<sup class="reference" id="cite_ref-55"><a href="#cite_note-55">[55]</a></sup><sup class="reference" id="cite_ref-56"><a href="#cite_note-56">[56]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">13
 </td>
 <td><a href="/wiki/One_Willoughby_Square" title="One Willoughby Square">One Willoughby Square</a>
 </td>
 <td><a class="image" href="/wiki/File:1WilloughbySII.jpg" title="1 Willoughby Square"><img alt="1 Willoughby Square" data-file-height="4032" data-file-width="3024" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/1WilloughbySII.jpg/80px-1WilloughbySII.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/1WilloughbySII.jpg/120px-1WilloughbySII.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/2a/1WilloughbySII.jpg/160px-1WilloughbySII.jpg 2x" width="80"/></a>
 </td>
 <td>495 (151)
 </td>
 <td>34
 </td>
 <td>2021
 </td>
 <td align="left">Originally planned as a 65-story residential development, the building is now under construction as a 34-story commercial and office space.<sup class="reference" id="cite_ref-20190310newyorkyimby_57-0"><a href="#cite_note-20190310newyorkyimby-57">[57]</a></sup> Topped out in October 2019, and is Brooklyn's tallest office building.<sup class="reference" id="cite_ref-20191004curbed-20897221_58-0"><a href="#cite_note-20191004curbed-20897221-58">[58]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">14
 </td>
 <td>66 Rockwell Place
 </td>
 <td><a class="image" href="/wiki/File:66RockwellBRK.jpg" title="66 Rockwell Place"><img alt="66 Rockwell Place, a high-rise clad in a façade of blue glass, viewed from street level" data-file-height="1632" data-file-width="918" decoding="async" height="142" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/06/66RockwellBRK.jpg/80px-66RockwellBRK.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/06/66RockwellBRK.jpg/120px-66RockwellBRK.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/06/66RockwellBRK.jpg/160px-66RockwellBRK.jpg 2x" width="80"/></a>
 </td>
 <td>489 (149)
 </td>
 <td>44
 </td>
 <td>2014
 </td>
 <td align="left"><sup class="reference" id="cite_ref-Emporis1151351_59-0"><a href="#cite_note-Emporis1151351-59">[59]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter11371_60-0"><a href="#cite_note-SkyscraperCenter11371-60">[60]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">15
 </td>
 <td><a href="/wiki/The_Alloy_Block" title="The Alloy Block">The Alloy Block - Phase One (100 Flatbush)</a>
 </td>
 <td>—
 </td>
 <td>482 (147)
 </td>
 <td>44
 </td>
 <td>2023
 </td>
 <td align="left">Topped out in January 2023.<sup class="reference" id="cite_ref-61"><a href="#cite_note-61">[61]</a></sup><sup class="reference" id="cite_ref-62"><a href="#cite_note-62">[62]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">16
 </td>
 <td>12 Metrotech Center
 </td>
 <td><a class="image" href="/wiki/File:Supreme_n_Family_Court_Jay_St_jeh.jpg" title="12 Metrotech Center"><img alt="12 Metrotech Center, a high-rise clad in a façade of stone and limestone, viewed from street level" data-file-height="4224" data-file-width="3168" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/89/Supreme_n_Family_Court_Jay_St_jeh.jpg/80px-Supreme_n_Family_Court_Jay_St_jeh.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/89/Supreme_n_Family_Court_Jay_St_jeh.jpg/120px-Supreme_n_Family_Court_Jay_St_jeh.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/89/Supreme_n_Family_Court_Jay_St_jeh.jpg/160px-Supreme_n_Family_Court_Jay_St_jeh.jpg 2x" width="80"/></a>
 </td>
 <td>473 (144)
 </td>
 <td>32
 </td>
 <td>2005
 </td>
 <td align="left">Also known as the Kings County Supreme and Family Courthouse.<sup class="reference" id="cite_ref-Emporis101470_63-0"><a href="#cite_note-Emporis101470-63">[63]</a></sup><sup class="reference" id="cite_ref-SkyscraperCenter9840_64-0"><a href="#cite_note-SkyscraperCenter9840-64">[64]</a></sup>
 </td></tr>,
 <tr>
 <td style="word-spacing: -5px;">17
 </td>
 <td><a href="/wiki/Montague%E2%80%93Court_Building" title="Montague–Court Building">Montague–Court Building</a>
 </td>

### 4) Use `.select(...)` (and `[0]`) again to select the table's first row

... which is its header. (Reminder that the `<thead>` tag is optional. Wikipedia tables don't use it.)

In [59]:
soup.select('table tr')[0]('th')

[<th>Rank
 </th>,
 <th>Name<sup class="reference" id="ref_id1none"><a href="#endnote_id1none">[a]</a></sup>
 </th>,
 <th class="unsortable">Image
 </th>,
 <th data-sort-type="number">Height<br/><span style="font-size:85%;">ft (m)</span>
 </th>,
 <th>Floors
 </th>,
 <th>Year completed
 </th>,
 <th class="unsortable">Notes
 </th>]

### 5) Extract the column names from that header

Use `.strip()` to remove any leading or trailing whitespace from the names.

First, try doing this with a standard `for` loop:

In [68]:
headers = []

for header in soup.select('table tr')[0]('th'):
    headers.append(header.text.strip())

headers

['Rank',
 'Name[a]',
 'Image',
 'Heightft (m)',
 'Floors',
 'Year completed',
 'Notes']

Now try to do it with a list comprehension:

In [113]:
headers = [header.text.strip() for header in soup.select('table tr')[0]('th')]
headers

['Rank',
 'Name[a]',
 'Image',
 'Heightft (m)',
 'Floors',
 'Year completed',
 'Notes']

### 6) Select all non-header row *elements* from the table

Since the header was the first row, you'll want to skip that one. How many rows are there? (Check with your eyes that this number matches what you deduce from the rankings column in the browser-rendered table.)

In [78]:
len(soup.select('table')[0]('tr')[1:])

73

### 7) For each row, extract the text of each cell into a Python list

First, try this as two nested `for` loops:

In [118]:
buildings = []
rows = []

for row in soup.select('table')[0]('tr')[1:]:
    for cell in row.select('td'):
        rows.append(cell.text.strip())
    buildings.append(rows)

buildings

[['1',
  'The Brooklyn Tower',
  '',
  '1,073 (327)',
  '93',
  '2022',
  'Topped out in October 2021.[2][22][23][24]',
  '2',
  'Brooklyn Point',
  '',
  '720 (219)',
  '68',
  '2019',
  "The final phase of Extell's City Point development; topped out in April 2019, it is now the second tallest building in Brooklyn.[25] Also known as 138 Willoughby Street,[26][27] 1 City Point,[28] and City Point Tower III.[28][29][30]",
  '3',
  '11 Hoyt',
  '',
  '626 (191)',
  '51',
  '2020',
  "Topped out in June 2019.[31] A redevelopment of Macy's former footprint in Downtown Brooklyn, with a design seemingly inspired by 8 Spruce Street.[32][33]",
  '4',
  'The Hub',
  '',
  '611 (186)',
  '52',
  '2017',
  'Also known as 333 Schermerhorn Street. Topped out on December 16, 2015.[34][35][36][37][38]',
  '5',
  'AVA DoBro',
  '',
  '596 (182)',
  '58',
  '2015',
  'Also known as 100 Willoughby Street, Avalon Willoughby Square, and 214 Duffield Street.[39][40][41]',
  '6',
  '388 Bridge Street',
  '',
  '590 (180)',
  '51',
  '2014',
  '[39][42][43]',
  '7',
  '590 Fulton Street',
  '',
  '568 (173)',
  '52',
  '2016',
  'Also known as 250 Ashland Place and Gotham BAM Tower[44][45][46]',
  '8',
  '18 Sixth Avenue',
  '—',
  '532 (162)',
  '49',
  '2022',
  'Also known as the Pacific Park B4 Tower.[47][48][49]',
  '9',
  'City Tower',
  '',
  '515 (157)',
  '46',
  '2016',
  'Also known as City Point Tower II,[50] 10 City Point, and 336 Flatbush Avenue Extension[51]',
  '10',
  'The Brooklyner',
  '',
  '514 (157)',
  '51',
  '2010',
  'Tallest high-rise building in Brooklyn between 2009 and 2013.[3][4][52][53]',
  '11',
  'Williamsburgh Savings Bank Tower',
  '',
  '512 (156)',
  '42',
  '1929',
  'Tallest high-rise building in Brooklyn between 1929 and 2009. Also known as One Hanson Place.[5][54]',
  '12',
  '540 Fulton Street',
  '',
  '511 (156)',
  '43',
  '2020',
  'Topped out in 2019.[55][56]',
  '13',
  'One Willoughby Square',
  '',
  '495 (151)',
  '34',
  '2021',
  "Originally planned as a 65-story residential development, the building is now under construction as a 34-story commercial and office space.[57] Topped out in October 2019, and is Brooklyn's tallest office building.[58]",
  '14',
  '66 Rockwell Place',
  '',
  '489 (149)',
  '44',
  '2014',
  '[59][60]',
  '15',
  'The Alloy Block - Phase One (100 Flatbush)',
  '—',
  '482 (147)',
  '44',
  '2023',
  'Topped out in January 2023.[61][62]',
  '16',
  '12 Metrotech Center',
  '',
  '473 (144)',
  '32',
  '2005',
  'Also known as the Kings County Supreme and Family Courthouse.[63][64]',
  '17',
  'Montague–Court Building',
  '',
  '462 (141)',
  '35',
  '1927',
  'Tallest high-rise building in Brooklyn between 1927 and 1929. Also known as 16 Court Street.[17][65]',
  '18',
  'Calyer Place Tower I',
  '—',
  '439 (134)',
  '40',
  '2022',
  '[66][67]',
  '19',
  '196 Willoughby Street',
  '',
  '435 (133)',
  '34',
  '2020',
  '[68]',
  '20',
  '260 Kent Avenue',
  '—',
  '435 (133)',
  '45',
  '2019',
  'Also known as One South First. Topped out in May 2019.[69] The skyscraper will be the second structure to be developed as part of the Domino Sugar Factory redevelopment plan.[70][71]',
  '21',
  'Oro',
  '',
  '432 (132)',
  '40',
  '2008',
  '[72][73]',
  '22',
  'Toren',
  '',
  '427 (130)',
  '37',
  '2009',
  '[74][75]',
  '23',
  'The Amberly',
  '',
  '425 (130)',
  '33',
  '2017',
  'Also known as 120 Nassau Street[1][76][77]',
  '24',
  '1 Metrotech Center',
  '',
  '412 (126)',
  '23',
  '1992',
  '[78][79]',
  '25',
  '664 Pacific Street',
  '—',
  '412 (126)',
  '26',
  '2020',
  'Alternately addressed as 37 Sixth Avenue or 495 Dean Street.[80][81]',
  '26',
  '1 Clinton Street',
  '',
  '409 (125)',
  '38',
  '2019',
  'Also known as 280 Cadman Plaza West. Will replace a branch of the Brooklyn Public Library. Topped out in March 2019.[82][83][84]',
  '27',
  'DKLB BKLN',
  '',
  '405 (123)',
  '34',
  '2010',
  'Also known as 80 DeKalb Avenue.[85][86]',
  '28',
  '87 Commercial Street',
  '—',
  '402 (123)',
  '40',
  '2022',
  '[87][88][89]',
  '29 =',
  'One Pierrepont Plaza',
  '',
  '400 (122)',
  '21',
  '1988',
  '[90]',
  '29 =',
  'BKLYN AIR',
  '',
  '400 (122)',
  '39',
  '2014',
  'Also known as Oro 2 Condominium.[91][92][93][94]',
  '29 =',
  '41 Blue Slip',
  '',
  '400 (122)',
  '40',
  '2020',
  'Topped out in May 2019.[95][96][97]',
  '29 =',
  'Greenpoint Block D 40 Story Tower',
  '',
  '400 (122)',
  '40',
  '2022',
  'Informally known as the Tetris buildings.[98][99] Alternately addressed as 221 West Street. Topped-out in April 2021.[100]',
  '29 =',
  '30 Front Street',
  '—',
  '400 (122)',
  '26',
  '2022',
  'Topped out in August 2021.[101][102]',
  '34 =',
  'Brooklyn Renaissance Plaza',
  '',
  '398 (121)',
  '32',
  '1998',
  'Also known as the New York Marriott at the Brooklyn Bridge.[103][104]',
  '34 =',
  '1 North 4th Place',
  '',
  '398 (121)',
  '41',
  '2014',
  'Also known as Three Northside Piers, 1N4th, and One North Fourth.[105][106]',
  '34 =',
  '2 North 6th Place',
  '—',
  '398 (121)',
  '40',
  '2016',
  '[107]',
  '37',
  '4 Metrotech Center',
  '',
  '394 (120)',
  '25',
  '1993',
  'Part of the MetroTech Center development[108][109]',
  '38',
  'Avalon Fort Greene',
  '',
  '393 (120)',
  '42',
  '2010',
  '[110][111]',
  '39',
  'The Greenpoint*',
  '',
  '392 (119)',
  '39',
  '2018',
  'Also known as 10 Huron and 21 India Street[112][113]',
  '40',
  "Jehovah's Witnesses Dormitory",
  '',
  '378 (115)',
  '30',
  '1995',
  '[114][115]',
  '41',
  '1 Bell Slip',
  '—',
  '369 (112)',
  '31',
  '2022',
  '[116][117]',
  '42',
  '300 Ashland',
  '',
  '364 (111)',
  '32',
  '2016',
  'Also known as Brooklyn Academy of Music South (BAM South) and 286 Ashland Place.[118]',
  '43',
  '7 DeKalb Avenue',
  '',
  '361 (110)',
  '27',
  '2016',
  'Also known as City Point Tower I[119] and 70 Fleet Street.[120]',
  '44',
  '141 Willoughby Street',
  '',
  '360 (110)',
  '24',
  '2022',
  'Topped out in November 2021.[121] Former site of the Institute of Design and Construction.[122][123]',
  '45',
  '2230 Cropsey Avenue',
  '—',
  '356 (109)',
  '30',
  '2023',
  'Topped out in February 2023.[124][125]',
  '46',
  'Court and Remsen Building',
  '',
  '350 (107)',
  '27',
  '1926',
  'Tallest high-rise building in Brooklyn between 1922 and 1926. Also known as the Chamber of Commerce Building.[12][126][127]',
  '47',
  'BellTel Lofts',
  '',
  '348 (106)',
  '25',
  '1931',
  'Also known as the New York Telephone Company Building and 101 Willoughby Street.[128][129]',
  '48',
  '461 Dean Street',
  '',
  '347 (106)',
  '32',
  '2016',
  'Also known as B2 BKLYN.[130]',
  '49',
  '86 Fleet Place',
  '',
  '346 (105)',
  '32',
  '2017',
  '[131]',
  '50',
  '75 Livingston Street',
  '',
  '343 (105)',
  '30',
  '1926',
  'Also known as the Brooklyn Chamber of Commerce and Court Chambers Building.[132][133][134]',
  '51',
  'Tivoli Towers',
  '',
  '341 (104)',
  '33',
  '1974',
  '[135][136]',
  '52',
  '37 Blue Slip',
  '',
  '340 (104)',
  '30',
  '2018',
  'Also known as One Blue Slip.[137][138]',
  '53',
  'J Condominium',
  '',
  '337 (103)',
  '31',
  '2007',
  'Also known as J Condo.[139][140]',
  '54',
  '200 Cadman Plaza',
  '',
  '333 (101)',
  '33',
  '1973',
  '[141]',
  '55',
  'Archstone Brooklyn Heights',
  '',
  '331 (101)',
  '33',
  '2000',
  'Also known as 180 Montague Street.[142]',
  '56',
  'Two Northside Piers',
  '',
  '329 (100)',
  '30',
  '2009',
  '[143]',
  '57',
  '15 Metrotech Center',
  '',
  '325 (99)',
  '21',
  '2003',
  'Also known as the Empire Blue Cross Blue Shield Headquarters.[144][145]',
  '58',
  '1524 Sheepshead Bay Road',
  '',
  '321 (98)',
  '28',
  '2018',
  'Also known as 1 Brooklyn Bay, Avalon Brooklyn Bay, and 1501 Voorhies Avenue.[146][147]',
  '59',
  '123 Linden Boulevard',
  '—',
  '320 (98)',
  '26',
  '2020',
  '[148]',
  '60 =',
  'St. George Towers',
  '',
  '315 (96)',
  '30',
  '1930',
  'Also known as the St. George Hotel.[149][150]',
  '60 =',
  'Quay Tower',
  '—',
  '315 (96)',
  '28',
  '2018',
  'Also known as 50 Bridge Park Drive.[151]',
  '60 =',
  '550 Clinton Avenue',
  '—',
  '312 (95)',
  '29',
  '2021',
  '[152][153]',
  '63 =',
  'Atlantic Terminal Houses 1',
  '',
  '310 (94)',
  '31',
  '1976',
  'Also known as Atlantic Terminal Site 4B and 487 Carlton Avenue.[154][155]',
  '63 =',
  '436 Albee Square',
  '',
  '310 (94)',
  '28',
  '2017',
  '[156]',
  '65',
  '77 Commercial Street',
  '—',
  '306 (93)',
  '30',
  '2022',
  '[88][89][87]',
  '66',
  '111 Livingston Street',
  '',
  '301 (92)',
  '23',
  '1971',
  '[157][158]',
  '67',
  'Greenpoint Block D 30 Story Tower',
  '',
  '300 (91)',
  '30',
  '2022',
  'Informally known as the Tetris buildings. Alternately addressed as 221 West Street. Topped-out in April 2021.[98][99][100]',
  '68',
  'The Edge – South Tower',
  '',
  '298 (91)',
  '30',
  '2009',
  'Also known as The Edge I.[159][160]',
  '69',
  '595 Dean Street',
  '—',
  '298 (91)',
  '27',
  '2022',
  'Topped out in February 2022.[161][162]',
  '70 =',
  'Beacon Tower',
  '',
  '297 (91)',
  '23',
  '2007',
  '[163][164]',
  '70 =',
  'One Northside Piers',
  '',
  '297 (91)',
  '29',
  '2008',
  '[165][166]',
  '70 =',
  '101 Clark Street',
  '—',
  '295 (90)',
  '30',
  '1973',
  '[167][168]',
  '70 =',
  '240 Willoughby Street',
  '—',
  '295 (90)',
  '30',
  '2023',
  'Topped out.[169][170]'],
 ['1',
  'The Brooklyn Tower',
  '',
  '1,073 (327)',
  '93',
  '2022',
  'Topped out in October 2021.[2][22][23][24]',
  '2',
  'Brooklyn Point',
  '',
  '720 (219)',
  '68',
  '2019',
  "The final phase of Extell's City Point development; topped out in April 2019, it is now the second tallest building in Brooklyn.[25] Also known as 138 Willoughby Street,[26][27] 1 City Point,[28] and City Point Tower III.[28][29][30]",
  '3',
  '11 Hoyt',
  '',
  '626 (191)',
  '51',
  '2020',
  "Topped out in June 2019.[31] A redevelopment of Macy's former footprint in Downtown Brooklyn, with a design seemingly inspired by 8 Spruce Street.[32][33]",
  '4',
  'The Hub',
  '',
  '611 (186)',
  '52',
  '2017',
  'Also known as 333 Schermerhorn Street. Topped out on December 16, 2015.[34][35][36][37][38]',
  '5',
  'AVA DoBro',
  '',
  '596 (182)',
  '58',
  '2015',
  'Also known as 100 Willoughby Street, Avalon Willoughby Square, and 214 Duffield Street.[39][40][41]',
  '6',
  '388 Bridge Street',
  '',
  '590 (180)',
  '51',
  '2014',
  '[39][42][43]',
  '7',
  '590 Fulton Street',
  '',
  '568 (173)',
  '52',
  '2016',
  'Also known as 250 Ashland Place and Gotham BAM Tower[44][45][46]',
  '8',
  '18 Sixth Avenue',
  '—',
  '532 (162)',
  '49',
  '2022',
  'Also known as the Pacific Park B4 Tower.[47][48][49]',
  '9',
  'City Tower',
  '',
  '515 (157)',
  '46',
  '2016',
  'Also known as City Point Tower II,[50] 10 City Point, and 336 Flatbush Avenue Extension[51]',
  '10',
  'The Brooklyner',
  '',
  '514 (157)',
  '51',
  '2010',
  'Tallest high-rise building in Brooklyn between 2009 and 2013.[3][4][52][53]',
  '11',
  'Williamsburgh Savings Bank Tower',
  '',
  '512 (156)',
  '42',
  '1929',
  'Tallest high-rise building in Brooklyn between 1929 and 2009. Also known as One Hanson Place.[5][54]',
  '12',
  '540 Fulton Street',
  '',
  '511 (156)',
  '43',
  '2020',
  'Topped out in 2019.[55][56]',
  '13',
  'One Willoughby Square',
  '',
  '495 (151)',
  '34',
  '2021',
  "Originally planned as a 65-story residential development, the building is now under construction as a 34-story commercial and office space.[57] Topped out in October 2019, and is Brooklyn's tallest office building.[58]",
  '14',
  '66 Rockwell Place',
  '',
  '489 (149)',
  '44',
  '2014',
  '[59][60]',
  '15',
  'The Alloy Block - Phase One (100 Flatbush)',
  '—',
  '482 (147)',
  '44',
  '2023',
  'Topped out in January 2023.[61][62]',
  '16',
  '12 Metrotech Center',
  '',
  '473 (144)',
  '32',
  '2005',
  'Also known as the Kings County Supreme and Family Courthouse.[63][64]',
  '17',
  'Montague–Court Building',
  '',
  '462 (141)',
  '35',
  '1927',
  'Tallest high-rise building in Brooklyn between 1927 and 1929. Also known as 16 Court Street.[17][65]',
  '18',
  'Calyer Place Tower I',
  '—',
  '439 (134)',
  '40',
  '2022',
  '[66][67]',
  '19',
  '196 Willoughby Street',
  '',
  '435 (133)',
  '34',
  '2020',
  '[68]',
  '20',
  '260 Kent Avenue',
  '—',
  '435 (133)',
  '45',
  '2019',
  'Also known as One South First. Topped out in May 2019.[69] The skyscraper will be the second structure to be developed as part of the Domino Sugar Factory redevelopment plan.[70][71]',
  '21',
  'Oro',
  '',
  '432 (132)',
  '40',
  '2008',
  '[72][73]',
  '22',
  'Toren',
  '',
  '427 (130)',
  '37',
  '2009',
  '[74][75]',
  '23',
  'The Amberly',
  '',
  '425 (130)',
  '33',
  '2017',
  'Also known as 120 Nassau Street[1][76][77]',
  '24',
  '1 Metrotech Center',
  '',
  '412 (126)',
  '23',
  '1992',
  '[78][79]',
  '25',
  '664 Pacific Street',
  '—',
  '412 (126)',
  '26',
  '2020',
  'Alternately addressed as 37 Sixth Avenue or 495 Dean Street.[80][81]',
  '26',
  '1 Clinton Street',
  '',
  '409 (125)',
  '38',
  '2019',
  'Also known as 280 Cadman Plaza West. Will replace a branch of the Brooklyn Public Library. Topped out in March 2019.[82][83][84]',
  '27',
  'DKLB BKLN',
  '',
  '405 (123)',
  '34',
  '2010',
  'Also known as 80 DeKalb Avenue.[85][86]',
  '28',
  '87 Commercial Street',
  '—',
  '402 (123)',
  '40',
  '2022',
  '[87][88][89]',
  '29 =',
  'One Pierrepont Plaza',
  '',
  '400 (122)',
  '21',
  '1988',
  '[90]',
  '29 =',
  'BKLYN AIR',
  '',
  '400 (122)',
  '39',
  '2014',
  'Also known as Oro 2 Condominium.[91][92][93][94]',
  '29 =',
  '41 Blue Slip',
  '',
  '400 (122)',
  '40',
  '2020',
  'Topped out in May 2019.[95][96][97]',
  '29 =',
  'Greenpoint Block D 40 Story Tower',
  '',
  '400 (122)',
  '40',
  '2022',
  'Informally known as the Tetris buildings.[98][99] Alternately addressed as 221 West Street. Topped-out in April 2021.[100]',
  '29 =',
  '30 Front Street',
  '—',
  '400 (122)',
  '26',
  '2022',
  'Topped out in August 2021.[101][102]',
  '34 =',
  'Brooklyn Renaissance Plaza',
  '',
  '398 (121)',
  '32',
  '1998',
  'Also known as the New York Marriott at the Brooklyn Bridge.[103][104]',
  '34 =',
  '1 North 4th Place',
  '',
  '398 (121)',
  '41',
  '2014',
  'Also known as Three Northside Piers, 1N4th, and One North Fourth.[105][106]',
  '34 =',
  '2 North 6th Place',
  '—',
  '398 (121)',
  '40',
  '2016',
  '[107]',
  '37',
  '4 Metrotech Center',
  '',
  '394 (120)',
  '25',
  '1993',
  'Part of the MetroTech Center development[108][109]',
  '38',
  'Avalon Fort Greene',
  '',
  '393 (120)',
  '42',
  '2010',
  '[110][111]',
  '39',
  'The Greenpoint*',
  '',
  '392 (119)',
  '39',
  '2018',
  'Also known as 10 Huron and 21 India Street[112][113]',
  '40',
  "Jehovah's Witnesses Dormitory",
  '',
  '378 (115)',
  '30',
  '1995',
  '[114][115]',
  '41',
  '1 Bell Slip',
  '—',
  '369 (112)',
  '31',
  '2022',
  '[116][117]',
  '42',
  '300 Ashland',
  '',
  '364 (111)',
  '32',
  '2016',
  'Also known as Brooklyn Academy of Music South (BAM South) and 286 Ashland Place.[118]',
  '43',
  '7 DeKalb Avenue',
  '',
  '361 (110)',
  '27',
  '2016',
  'Also known as City Point Tower I[119] and 70 Fleet Street.[120]',
  '44',
  '141 Willoughby Street',
  '',
  '360 (110)',
  '24',
  '2022',
  'Topped out in November 2021.[121] Former site of the Institute of Design and Construction.[122][123]',
  '45',
  '2230 Cropsey Avenue',
  '—',
  '356 (109)',
  '30',
  '2023',
  'Topped out in February 2023.[124][125]',
  '46',
  'Court and Remsen Building',
  '',
  '350 (107)',
  '27',
  '1926',
  'Tallest high-rise building in Brooklyn between 1922 and 1926. Also known as the Chamber of Commerce Building.[12][126][127]',
  '47',
  'BellTel Lofts',
  '',
  '348 (106)',
  '25',
  '1931',
  'Also known as the New York Telephone Company Building and 101 Willoughby Street.[128][129]',
  '48',
  '461 Dean Street',
  '',
  '347 (106)',
  '32',
  '2016',
  'Also known as B2 BKLYN.[130]',
  '49',
  '86 Fleet Place',
  '',
  '346 (105)',
  '32',
  '2017',
  '[131]',
  '50',
  '75 Livingston Street',
  '',
  '343 (105)',
  '30',
  '1926',
  'Also known as the Brooklyn Chamber of Commerce and Court Chambers Building.[132][133][134]',
  '51',
  'Tivoli Towers',
  '',
  '341 (104)',
  '33',
  '1974',
  '[135][136]',
  '52',
  '37 Blue Slip',
  '',
  '340 (104)',
  '30',
  '2018',
  'Also known as One Blue Slip.[137][138]',
  '53',
  'J Condominium',
  '',
  '337 (103)',
  '31',
  '2007',
  'Also known as J Condo.[139][140]',
  '54',
  '200 Cadman Plaza',
  '',
  '333 (101)',
  '33',
  '1973',
  '[141]',
  '55',
  'Archstone Brooklyn Heights',
  '',
  '331 (101)',
  '33',
  '2000',
  'Also known as 180 Montague Street.[142]',
  '56',
  'Two Northside Piers',
  '',
  '329 (100)',
  '30',
  '2009',
  '[143]',
  '57',
  '15 Metrotech Center',
  '',
  '325 (99)',
  '21',
  '2003',
  'Also known as the Empire Blue Cross Blue Shield Headquarters.[144][145]',
  '58',
  '1524 Sheepshead Bay Road',
  '',
  '321 (98)',
  '28',
  '2018',
  'Also known as 1 Brooklyn Bay, Avalon Brooklyn Bay, and 1501 Voorhies Avenue.[146][147]',
  '59',
  '123 Linden Boulevard',
  '—',
  '320 (98)',
  '26',
  '2020',
  '[148]',
  '60 =',
  'St. George Towers',
  '',
  '315 (96)',
  '30',
  '1930',
  'Also known as the St. George Hotel.[149][150]',
  '60 =',
  'Quay Tower',
  '—',
  '315 (96)',
  '28',
  '2018',
  'Also known as 50 Bridge Park Drive.[151]',
  '60 =',
  '550 Clinton Avenue',
  '—',
  '312 (95)',
  '29',
  '2021',
  '[152][153]',
  '63 =',
  'Atlantic Terminal Houses 1',
  '',
  '310 (94)',
  '31',
  '1976',
  'Also known as Atlantic Terminal Site 4B and 487 Carlton Avenue.[154][155]',
  '63 =',
  '436 Albee Square',
  '',
  '310 (94)',
  '28',
  '2017',
  '[156]',
  '65',
  '77 Commercial Street',
  '—',
  '306 (93)',
  '30',
  '2022',
  '[88][89][87]',
  '66',
  '111 Livingston Street',
  '',
  '301 (92)',
  '23',
  '1971',
  '[157][158]',
  '67',
  'Greenpoint Block D 30 Story Tower',
  '',
  '300 (91)',
  '30',
  '2022',
  'Informally known as the Tetris buildings. Alternately addressed as 221 West Street. Topped-out in April 2021.[98][99][100]',
  '68',
  'The Edge – South Tower',
  '',
  '298 (91)',
  '30',
  '2009',
  'Also known as The Edge I.[159][160]',
  '69',
  '595 Dean Street',
  '—',
  '298 (91)',
  '27',
  '2022',
  'Topped out in February 2022.[161][162]',
  '70 =',
  'Beacon Tower',
  '',
  '297 (91)',
  '23',
  '2007',
  '[163][164]',
  '70 =',
  'One Northside Piers',
  '',
  '297 (91)',
  '29',
  '2008',
  '[165][166]',
  '70 =',
  '101 Clark Street',
  '—',
  '295 (90)',
  '30',
  '1973',
  '[167][168]',
  '70 =',
  '240 Willoughby Street',
  '—',
  '295 (90)',
  '30',
  '2023',
  'Topped out.[169][170]'],
 ['1',
  'The Brooklyn Tower',
  '',
  '1,073 (327)',
  '93',
  '2022',
  'Topped out in October 2021.[2][22][23][24]',
  '2',
  'Brooklyn Point',
  '',
  '720 (219)',
  '68',
  '2019',
  "The final phase of Extell's City Point development; topped out in April 2019, it is now the second tallest building in Brooklyn.[25] Also known as 138 Willoughby Street,[26][27] 1 City Point,[28] and City Point Tower III.[28][29][30]",
  '3',
  '11 Hoyt',
  '',
  '626 (191)',
  '51',
  '2020',
  "Topped out in June 2019.[31] A redevelopment of Macy's former footprint in Downtown Brooklyn, with a design seemingly inspired by 8 Spruce Street.[32][33]",
  '4',
  'The Hub',
  '',
  '611 (186)',
  '52',
  '2017',
  'Also known as 333 Schermerhorn Street. Topped out on December 16, 2015.[34][35][36][37][38]',
  '5',
  'AVA DoBro',
  '',
  '596 (182)',
  '58',
  '2015',
  'Also known as 100 Willoughby Street, Avalon Willoughby Square, and 214 Duffield Street.[39][40][41]',
  '6',
  '388 Bridge Street',
  '',
  '590 (180)',
  '51',
  '2014',
  '[39][42][43]',
  '7',

Now try with two list comprehensions, one nested in the other:

In [128]:
buildings = [[cell.text.strip() for cell in row.select('td')] for row in soup.select('table')[0]('tr')[1:]]

# buildings = [[cell.text.strip() for cell in row.select('td')] for row in soup.select('table')0[1:]

buildings

[['1',
  'The Brooklyn Tower',
  '',
  '1,073 (327)',
  '93',
  '2022',
  'Topped out in October 2021.[2][22][23][24]'],
 ['2',
  'Brooklyn Point',
  '',
  '720 (219)',
  '68',
  '2019',
  "The final phase of Extell's City Point development; topped out in April 2019, it is now the second tallest building in Brooklyn.[25] Also known as 138 Willoughby Street,[26][27] 1 City Point,[28] and City Point Tower III.[28][29][30]"],
 ['3',
  '11 Hoyt',
  '',
  '626 (191)',
  '51',
  '2020',
  "Topped out in June 2019.[31] A redevelopment of Macy's former footprint in Downtown Brooklyn, with a design seemingly inspired by 8 Spruce Street.[32][33]"],
 ['4',
  'The Hub',
  '',
  '611 (186)',
  '52',
  '2017',
  'Also known as 333 Schermerhorn Street. Topped out on December 16, 2015.[34][35][36][37][38]'],
 ['5',
  'AVA DoBro',
  '',
  '596 (182)',
  '58',
  '2015',
  'Also known as 100 Willoughby Street, Avalon Willoughby Square, and 214 Duffield Street.[39][40][41]'],
 ['6', '388 Bridge Street', '', '590 (180)', '51', '2014', '[39][42][43]'],
 ['7',
  '590 Fulton Street',
  '',
  '568 (173)',
  '52',
  '2016',
  'Also known as 250 Ashland Place and Gotham BAM Tower[44][45][46]'],
 ['8',
  '18 Sixth Avenue',
  '—',
  '532 (162)',
  '49',
  '2022',
  'Also known as the Pacific Park B4 Tower.[47][48][49]'],
 ['9',
  'City Tower',
  '',
  '515 (157)',
  '46',
  '2016',
  'Also known as City Point Tower II,[50] 10 City Point, and 336 Flatbush Avenue Extension[51]'],
 ['10',
  'The Brooklyner',
  '',
  '514 (157)',
  '51',
  '2010',
  'Tallest high-rise building in Brooklyn between 2009 and 2013.[3][4][52][53]'],
 ['11',
  'Williamsburgh Savings Bank Tower',
  '',
  '512 (156)',
  '42',
  '1929',
  'Tallest high-rise building in Brooklyn between 1929 and 2009. Also known as One Hanson Place.[5][54]'],
 ['12',
  '540 Fulton Street',
  '',
  '511 (156)',
  '43',
  '2020',
  'Topped out in 2019.[55][56]'],
 ['13',
  'One Willoughby Square',
  '',
  '495 (151)',
  '34',
  '2021',
  "Originally planned as a 65-story residential development, the building is now under construction as a 34-story commercial and office space.[57] Topped out in October 2019, and is Brooklyn's tallest office building.[58]"],
 ['14', '66 Rockwell Place', '', '489 (149)', '44', '2014', '[59][60]'],
 ['15',
  'The Alloy Block - Phase One (100 Flatbush)',
  '—',
  '482 (147)',
  '44',
  '2023',
  'Topped out in January 2023.[61][62]'],
 ['16',
  '12 Metrotech Center',
  '',
  '473 (144)',
  '32',
  '2005',
  'Also known as the Kings County Supreme and Family Courthouse.[63][64]'],
 ['17',
  'Montague–Court Building',
  '',
  '462 (141)',
  '35',
  '1927',
  'Tallest high-rise building in Brooklyn between 1927 and 1929. Also known as 16 Court Street.[17][65]'],
 ['18', 'Calyer Place Tower I', '—', '439 (134)', '40', '2022', '[66][67]'],
 ['19', '196 Willoughby Street', '', '435 (133)', '34', '2020', '[68]'],
 ['20',
  '260 Kent Avenue',
  '—',
  '435 (133)',
  '45',
  '2019',
  'Also known as One South First. Topped out in May 2019.[69] The skyscraper will be the second structure to be developed as part of the Domino Sugar Factory redevelopment plan.[70][71]'],
 ['21', 'Oro', '', '432 (132)', '40', '2008', '[72][73]'],
 ['22', 'Toren', '', '427 (130)', '37', '2009', '[74][75]'],
 ['23',
  'The Amberly',
  '',
  '425 (130)',
  '33',
  '2017',
  'Also known as 120 Nassau Street[1][76][77]'],
 ['24', '1 Metrotech Center', '', '412 (126)', '23', '1992', '[78][79]'],
 ['25',
  '664 Pacific Street',
  '—',
  '412 (126)',
  '26',
  '2020',
  'Alternately addressed as 37 Sixth Avenue or 495 Dean Street.[80][81]'],
 ['26',
  '1 Clinton Street',
  '',
  '409 (125)',
  '38',
  '2019',
  'Also known as 280 Cadman Plaza West. Will replace a branch of the Brooklyn Public Library. Topped out in March 2019.[82][83][84]'],
 ['27',
  'DKLB BKLN',
  '',
  '405 (123)',
  '34',
  '2010',
  'Also known as 80 DeKalb Avenue.[85][86]'],
 ['28',
  '87 Commercial Street',
  '—',
  '402 (123)',
  '40',
  '2022',
  '[87][88][89]'],
 ['29 =', 'One Pierrepont Plaza', '', '400 (122)', '21', '1988', '[90]'],
 ['29 =',
  'BKLYN AIR',
  '',
  '400 (122)',
  '39',
  '2014',
  'Also known as Oro 2 Condominium.[91][92][93][94]'],
 ['29 =',
  '41 Blue Slip',
  '',
  '400 (122)',
  '40',
  '2020',
  'Topped out in May 2019.[95][96][97]'],
 ['29 =',
  'Greenpoint Block D 40 Story Tower',
  '',
  '400 (122)',
  '40',
  '2022',
  'Informally known as the Tetris buildings.[98][99] Alternately addressed as 221 West Street. Topped-out in April 2021.[100]'],
 ['29 =',
  '30 Front Street',
  '—',
  '400 (122)',
  '26',
  '2022',
  'Topped out in August 2021.[101][102]'],
 ['34 =',
  'Brooklyn Renaissance Plaza',
  '',
  '398 (121)',
  '32',
  '1998',
  'Also known as the New York Marriott at the Brooklyn Bridge.[103][104]'],
 ['34 =',
  '1 North 4th Place',
  '',
  '398 (121)',
  '41',
  '2014',
  'Also known as Three Northside Piers, 1N4th, and One North Fourth.[105][106]'],
 ['34 =', '2 North 6th Place', '—', '398 (121)', '40', '2016', '[107]'],
 ['37',
  '4 Metrotech Center',
  '',
  '394 (120)',
  '25',
  '1993',
  'Part of the MetroTech Center development[108][109]'],
 ['38', 'Avalon Fort Greene', '', '393 (120)', '42', '2010', '[110][111]'],
 ['39',
  'The Greenpoint*',
  '',
  '392 (119)',
  '39',
  '2018',
  'Also known as 10 Huron and 21 India Street[112][113]'],
 ['40',
  "Jehovah's Witnesses Dormitory",
  '',
  '378 (115)',
  '30',
  '1995',
  '[114][115]'],
 ['41', '1 Bell Slip', '—', '369 (112)', '31', '2022', '[116][117]'],
 ['42',
  '300 Ashland',
  '',
  '364 (111)',
  '32',
  '2016',
  'Also known as Brooklyn Academy of Music South (BAM South) and 286 Ashland Place.[118]'],
 ['43',
  '7 DeKalb Avenue',
  '',
  '361 (110)',
  '27',
  '2016',
  'Also known as City Point Tower I[119] and 70 Fleet Street.[120]'],
 ['44',
  '141 Willoughby Street',
  '',
  '360 (110)',
  '24',
  '2022',
  'Topped out in November 2021.[121] Former site of the Institute of Design and Construction.[122][123]'],
 ['45',
  '2230 Cropsey Avenue',
  '—',
  '356 (109)',
  '30',
  '2023',
  'Topped out in February 2023.[124][125]'],
 ['46',
  'Court and Remsen Building',
  '',
  '350 (107)',
  '27',
  '1926',
  'Tallest high-rise building in Brooklyn between 1922 and 1926. Also known as the Chamber of Commerce Building.[12][126][127]'],
 ['47',
  'BellTel Lofts',
  '',
  '348 (106)',
  '25',
  '1931',
  'Also known as the New York Telephone Company Building and 101 Willoughby Street.[128][129]'],
 ['48',
  '461 Dean Street',
  '',
  '347 (106)',
  '32',
  '2016',
  'Also known as B2 BKLYN.[130]'],
 ['49', '86 Fleet Place', '', '346 (105)', '32', '2017', '[131]'],
 ['50',
  '75 Livingston Street',
  '',
  '343 (105)',
  '30',
  '1926',
  'Also known as the Brooklyn Chamber of Commerce and Court Chambers Building.[132][133][134]'],
 ['51', 'Tivoli Towers', '', '341 (104)', '33', '1974', '[135][136]'],
 ['52',
  '37 Blue Slip',
  '',
  '340 (104)',
  '30',
  '2018',
  'Also known as One Blue Slip.[137][138]'],
 ['53',
  'J Condominium',
  '',
  '337 (103)',
  '31',
  '2007',
  'Also known as J Condo.[139][140]'],
 ['54', '200 Cadman Plaza', '', '333 (101)', '33', '1973', '[141]'],
 ['55',
  'Archstone Brooklyn Heights',
  '',
  '331 (101)',
  '33',
  '2000',
  'Also known as 180 Montague Street.[142]'],
 ['56', 'Two Northside Piers', '', '329 (100)', '30', '2009', '[143]'],
 ['57',
  '15 Metrotech Center',
  '',
  '325 (99)',
  '21',
  '2003',
  'Also known as the Empire Blue Cross Blue Shield Headquarters.[144][145]'],
 ['58',
  '1524 Sheepshead Bay Road',
  '',
  '321 (98)',
  '28',
  '2018',
  'Also known as 1 Brooklyn Bay, Avalon Brooklyn Bay, and 1501 Voorhies Avenue.[146][147]'],
 ['59', '123 Linden Boulevard', '—', '320 (98)', '26', '2020', '[148]'],
 ['60 =',
  'St. George Towers',
  '',
  '315 (96)',
  '30',
  '1930',
  'Also known as the St. George Hotel.[149][150]'],
 ['60 =',
  'Quay Tower',
  '—',
  '315 (96)',
  '28',
  '2018',
  'Also known as 50 Bridge Park Drive.[151]'],
 ['60 =', '550 Clinton Avenue', '—', '312 (95)', '29', '2021', '[152][153]'],
 ['63 =',
  'Atlantic Terminal Houses 1',
  '',
  '310 (94)',
  '31',
  '1976',
  'Also known as Atlantic Terminal Site 4B and 487 Carlton Avenue.[154][155]'],
 ['63 =', '436 Albee Square', '', '310 (94)', '28', '2017', '[156]'],
 ['65', '77 Commercial Street', '—', '306 (93)', '30', '2022', '[88][89][87]'],
 ['66', '111 Livingston Street', '', '301 (92)', '23', '1971', '[157][158]'],
 ['67',
  'Greenpoint Block D 30 Story Tower',
  '',
  '300 (91)',
  '30',
  '2022',
  'Informally known as the Tetris buildings. Alternately addressed as 221 West Street. Topped-out in April 2021.[98][99][100]'],
 ['68',
  'The Edge – South Tower',
  '',
  '298 (91)',
  '30',
  '2009',
  'Also known as The Edge I.[159][160]'],
 ['69',
  '595 Dean Street',
  '—',
  '298 (91)',
  '27',
  '2022',
  'Topped out in February 2022.[161][162]'],
 ['70 =', 'Beacon Tower', '', '297 (91)', '23', '2007', '[163][164]'],
 ['70 =', 'One Northside Piers', '', '297 (91)', '29', '2008', '[165][166]'],
 ['70 =', '101 Clark Street', '—', '295 (90)', '30', '1973', '[167][168]'],
 ['70 =',
  '240 Willoughby Street',
  '—',
  '295 (90)',
  '30',
  '2023',
  'Topped out.[169][170]']]

### 8) Turn the data you've extracted into a `pandas` `DataFrame`

In [257]:
df = pd.DataFrame(buildings, columns=headers)
df

,Rank,Name[a],Image,Heightft (m),Floors,Year completed,Notes
0,1,The Brooklyn Tower,,"1,073 (327)",93,2022,Topped out in October 2021.[2][22][23][24]
1,2,Brooklyn Point,,720 (219),68,2019,The final phase of Extell's City Point develop...
2,3,11 Hoyt,,626 (191),51,2020,Topped out in June 2019.[31] A redevelopment o...
3,4,The Hub,,611 (186),52,2017,Also known as 333 Schermerhorn Street. Topped ...
4,5,AVA DoBro,,596 (182),58,2015,"Also known as 100 Willoughby Street, Avalon Wi..."
...,...,...,...,...,...,...,...
68,69,595 Dean Street,—,298 (91),27,2022,Topped out in February 2022.[161][162]
69,70 =,Beacon Tower,,297 (91),23,2007,[163][164]
70,70 =,One Northside Piers,,297 (91),29,2008,[165][166]
71,70 =,101 Clark Street,—,295 (90),30,1973,[167][168]
72,70 =,240 Willoughby Street,—,295 (90),30,2023,Topped out.[169][170]

### 9) Which years are represented by at least 5 buildings?

In [146]:
df['Year completed'].value_counts().head(4)

Year completed
2022    11
2020     6
2016     6
2017     4
Name: count, dtype: int64

### 10) How many total floors do all the buildings have, combined?

In [158]:
df['Floors'] = df['Floors'].astype('int')

print(df['Floors'].sum())

2603

### 11) How many of the buildings have their own Wikipedia page?

For this, you'll need to query the row elements again; the information won't have been extracted into your `DataFrame`. (Hint: Whether a building has its own Wikipedia page isn't an explicit piece of data, but something you can infer from the presence of a particular sub-element.)

In [230]:
# for row in soup.select('table')[0]('tr a'):
#     print(row)

# for row in soup.select('table')[0]('tr')[1:]:
#     print (row.select('td')[1]('a'))
#     print('-------')

links = [(row.select('td')[1]('a')) for row in soup.select('table')[0]('tr')[1:] if row.select('td')[1].find('a')]
len(links)

17

### 12) How many have an image?

You could do this by testing for the presence of another element:

In [241]:
for row in soup.select('table')[0]('tr')[1:2]:
    print(row.select('td')[2])

<td><a class="image" href="/wiki/File:The_Brooklyn_Tower_010.jpg" title="City Point"><img alt="A view of The Brooklyn Tower looking north from Bond Street" data-file-height="2048" data-file-width="1536" decoding="async" height="107" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/80px-The_Brooklyn_Tower_010.jpg" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/120px-The_Brooklyn_Tower_010.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_Brooklyn_Tower_010.jpg/160px-The_Brooklyn_Tower_010.jpg 2x" width="80"/></a>
</td>

In [249]:
# for row in soup.select('table')[0]('tr')[1:]:
#     print(row.select('td')[2])


len ([(row.select('.image')) for row in soup.select('table')[0]('tr')[1:] if row.select('.image')])

56

Or through information that's already in your `DataFrame`:

In [263]:
df['Image'].value_counts()

Image
     56
—    17
Name: count, dtype: int64

### Bonus challenge

If we tried to run the same code on https://en.wikipedia.org/wiki/List_of_tallest_buildings_in_New_York_City instead, the results wouldn't be quite right. Try it. Then, examining the HTML of that page, try to figure out why.

If you want an extra-extra challenge, try writing code that would parse that table correctly.

In [272]:
url2 = requests.get('https://en.wikipedia.org/wiki/List_of_tallest_buildings_in_New_York_City')
html_2 = url2.text
soup2 = BeautifulSoup(html_2)

headers2 = [header.text.strip() for header in soup2.select('table tr')[0]('th')]
buildings2 = [[cell.text.strip() for cell in row.select('td')] for row in soup2.select('table')[0]('tr')[1:]]
len(buildings)

106

In [275]:
df2 = pd.DataFrame(buildings2, columns=headers2)
df2

,Rank,Name,Image,Heightft (m),Floors[H],Year,Address,Coordinates,Notes
0,1,One World Trade Center,,"1,776 (541)",94[A],2014,285 Fulton Street,40°42′47″N 74°00′49″W﻿ / ﻿40.713°N 74.0135°W﻿ ...,Also known as the Freedom Tower. Tallest build...
1,2,Central Park Tower,,"1,550 (472)",99,2021,225 West 57th Street,40°45′57″N 73°58′51″W﻿ / ﻿40.7659°N 73.98089°W...,"Also known as Nordstrom Tower. At 1,550 feet, ..."
2,3,111 West 57th Street,,"1,428 (435)",85,2022,111 West 57th Street,40°45′52″N 73°58′40″W﻿ / ﻿40.76455°N 73.97765°...,Also known as Steinway Tower. It is the world'...
3,4,One Vanderbilt,,"1,401 (427)",73,2020,1 Vanderbilt Avenue,40°45′11″N 73°58′43″W﻿ / ﻿40.7530°N 73.9785°W﻿...,Second tallest office building in NYC.[38] Tal...
4,5,432 Park Avenue,,"1,397 (426)",85,2015,432 Park Avenue,40°45′41″N 73°58′19″W﻿ / ﻿40.761389°N 73.97180...,"Fifth tallest building overall in NYC, third t..."
...,...,...,...,...,...,...,...,...,...
101,102,1 Wall Street,,654 (199),50,1932,1 Wall Street,40°42′26″N 74°00′42″W﻿ / ﻿40.707222°N 74.01166...,It was formerly called Bank of New York Buildi...
102,103 =,599 Lexington Avenue,,653 (199),51,1986,599 Lexington Avenue,40°45′28″N 73°58′15″W﻿ / ﻿40.7578°N 73.9707°W﻿...,[240][241]
103,103 =,Silver Towers I,,653 (199),58,2009,620 West 42nd Street,40°45′39″N 73°59′57″W﻿ / ﻿40.760722°N 73.99919...,Also known as River Place.[242][243]
104,103 =,Silver Towers II,653 (199),58,2009,620 West 42nd Street,40°45′39″N 73°59′57″W﻿ / ﻿40.760722°N 73.99919...,Also known as River Place.[244][245],None
105,106,712 Fifth Avenue,,650 (198),53,1990,712 Fifth Avenue,40°45′44″N 73°58′30″W﻿ / ﻿40.7622°N 73.975°W﻿ ...,[246][247]

---

---

---