# Cleaning Data: Homework

In class, we discussed a few different ways to clean data — simple Python methods, Pandas versions of those methods, and regular expressions (both in plain Python and in Pandas). You are welcome to use whatever combination of those approaches you'd like. If you really want to stretch your skills, try solving the questions a few different ways.

## 0) Load `pets.csv` (provided in CourseWorks)

... and assign the data to a variable named `pets`.

In [11]:
import pandas as pd
pets = pd.read_csv('pets.csv')
pets

               name    species  weight years_old
0       smith, fido        dog   5 lbs        1
1     SMITH,, Bella        CAT   7 lbs        10
2       Ortiz, Milo        dog  15 lbs         5
3     Smith, Goldie   goldfish    7 oz       ???
4         Kim, Fuzz        cat   3 lbs  5 (five)
5  Jones, Las Vegas        DOG  12 lbs   unknown
6       Jones; fifi      puppy   2 lbs      0.25
7         Lee, nemo  gold fish   10 oz         2
8       Chan, ZIGGY     kitten   2 lbs       0.5
9         Chan, Zog        dog  20 lbs         7

We're going to clean the data so that you can __programmatically__ answer the following questions:

- Which family owns the most pets? (All pets have been given the surname of the family that owns them. Assume that there's only one family with each surname.)
---
- How many of each kind of animal are there? (Puppies should count as dogs, and kittens as cats.)
---
- What is the total weight of the pets? (And which family's pets weigh the most, total?)
---
- Of the *known* ages, what's the average pet age?

## 1) Create a new column in the DataFrame called `last_name`, containing *just* the pet's surname

... normalized so that `.value_counts()` will count `smith, fido` and `SMITH, Bella` as being from the same family.

In [93]:
last_names = []

for name in df['name']:
    name = name.split(',')[0].split(';')[0].lower()
    last_names.append(name)

pets['last_name'] = last_names
pets

               name    species  weight years_old last_name
0       smith, fido        dog   5 lbs        1      smith
1     SMITH,, Bella        CAT   7 lbs        10     smith
2       Ortiz, Milo        dog  15 lbs         5     ortiz
3     Smith, Goldie   goldfish    7 oz       ???     smith
4         Kim, Fuzz        cat   3 lbs  5 (five)       kim
5  Jones, Las Vegas        DOG  12 lbs   unknown     jones
6       Jones; fifi      puppy   2 lbs      0.25     jones
7         Lee, nemo  gold fish   10 oz         2       lee
8       Chan, ZIGGY     kitten   2 lbs       0.5      chan
9         Chan, Zog        dog  20 lbs         7      chan

## 2) Check how many distinct last names you see

(There should be 6.)

In [47]:
pets['last_name'].unique()

array(['smith', 'ortiz', 'kim', 'jones', 'lee', 'chan'], dtype=object)

## 3) Calculate which family owns the most pets

(All pets have been given the surname of the family that owns them. Assume that there's only one family with each surname.)

In [46]:
pets['last_name'].value_counts()

last_name
smith    3
jones    2
chan     2
ortiz    1
kim      1
lee      1
Name: count, dtype: int64

## 4) Create a new column called `animal_type`, which standardizes the `species` column

(Puppies should count as dogs, and kittens as cats; and there should only be one spelling of `gold fish`/`goldfish`.)

In [94]:
species = []

for specie in pets['species']:
    specie = specie.lower()
    if specie == 'puppy':
        specie = 'dog'
    elif specie == 'kitten':
        specie = 'cat'
    elif specie == 'gold fish':
        specie = 'goldfish'
    species.append(specie)
        
pets['animal_type'] = species
pets

               name    species  weight years_old last_name animal_type
0       smith, fido        dog   5 lbs        1      smith         dog
1     SMITH,, Bella        CAT   7 lbs        10     smith         cat
2       Ortiz, Milo        dog  15 lbs         5     ortiz         dog
3     Smith, Goldie   goldfish    7 oz       ???     smith    goldfish
4         Kim, Fuzz        cat   3 lbs  5 (five)       kim         cat
5  Jones, Las Vegas        DOG  12 lbs   unknown     jones         dog
6       Jones; fifi      puppy   2 lbs      0.25     jones         dog
7         Lee, nemo  gold fish   10 oz         2       lee    goldfish
8       Chan, ZIGGY     kitten   2 lbs       0.5      chan         cat
9         Chan, Zog        dog  20 lbs         7      chan         dog

## 5) How many of each kind of animal are there?

In [118]:
pets['animal_type'].value_counts()

animal_type
dog         5
cat         3
goldfish    2
Name: count, dtype: int64

## 6) Create a new column called `weight_quantity`, which represents the numeric component of the `weight` column, as an integer

(i.e., `"10 oz"` -> `10`)

In [96]:
pets['weight_quantity'] = df['weight'].str.split(' ').str[0]
pets

,name,species,weight,years_old,last_name,animal_type,weight_quantity
0,"smith, fido",dog,5 lbs,1,smith,dog,5
1,"SMITH,, Bella",CAT,7 lbs,10,smith,cat,7
2,"Ortiz, Milo",dog,15 lbs,5,ortiz,dog,15
3,"Smith, Goldie",goldfish,7 oz,???,smith,goldfish,7
4,"Kim, Fuzz",cat,3 lbs,5 (five),kim,cat,3
5,"Jones, Las Vegas",DOG,12 lbs,unknown,jones,dog,12
6,Jones; fifi,puppy,2 lbs,0.25,jones,dog,2
7,"Lee, nemo",gold fish,10 oz,2,lee,goldfish,10
8,"Chan, ZIGGY",kitten,2 lbs,0.5,chan,cat,2
9,"Chan, Zog",dog,20 lbs,7,chan,dog,20

## 7) Create a new column called `weight_unit`, which represents the units component of the `weight` column

(i.e., `"10 oz"` -> `"oz"`)

In [97]:
pets['weight_unit'] = pets['weight'].str.split(' ').str[1]
pets

,name,species,weight,years_old,last_name,animal_type,weight_quantity,weight_unit
0,"smith, fido",dog,5 lbs,1,smith,dog,5,lbs
1,"SMITH,, Bella",CAT,7 lbs,10,smith,cat,7,lbs
2,"Ortiz, Milo",dog,15 lbs,5,ortiz,dog,15,lbs
3,"Smith, Goldie",goldfish,7 oz,???,smith,goldfish,7,oz
4,"Kim, Fuzz",cat,3 lbs,5 (five),kim,cat,3,lbs
5,"Jones, Las Vegas",DOG,12 lbs,unknown,jones,dog,12,lbs
6,Jones; fifi,puppy,2 lbs,0.25,jones,dog,2,lbs
7,"Lee, nemo",gold fish,10 oz,2,lee,goldfish,10,oz
8,"Chan, ZIGGY",kitten,2 lbs,0.5,chan,cat,2,lbs
9,"Chan, Zog",dog,20 lbs,7,chan,dog,20,lbs

## 8) Create a new column called `unit_factor`, which should equal `1` when `weight_unit` is `"lbs"` and `0.0625` when `weight_unit` is `"oz"`

(i.e., `"10 oz"` -> `"oz"`)

You could do this by defining a function and using `column.apply(my_function)` or through Pandas' `.replace({ ... })` method, which we didn't cover in class but is somewhat easier here. That would look like this (yes, I'm giving you the answer here):

```python
pets["unit_factor"] = (
    pets["weight_unit"]
    .replace({
        "lbs": 1,
        "oz": 0.0625
    })
)
```

In [99]:
def get_conversion(weight):
    if "lbs" in weight:
        conversion = 1
    elif "oz" in weight:
        conversion = 0.0625
    return conversion

pets['unit_factor'] = df['weight'].apply(get_conversion)
pets

,name,species,weight,years_old,last_name,animal_type,weight_quantity,weight_unit,unit_factor
0,"smith, fido",dog,5 lbs,1,smith,dog,5,lbs,1.0000
1,"SMITH,, Bella",CAT,7 lbs,10,smith,cat,7,lbs,1.0000
2,"Ortiz, Milo",dog,15 lbs,5,ortiz,dog,15,lbs,1.0000
3,"Smith, Goldie",goldfish,7 oz,???,smith,goldfish,7,oz,0.0625
4,"Kim, Fuzz",cat,3 lbs,5 (five),kim,cat,3,lbs,1.0000
5,"Jones, Las Vegas",DOG,12 lbs,unknown,jones,dog,12,lbs,1.0000
6,Jones; fifi,puppy,2 lbs,0.25,jones,dog,2,lbs,1.0000
7,"Lee, nemo",gold fish,10 oz,2,lee,goldfish,10,oz,0.0625
8,"Chan, ZIGGY",kitten,2 lbs,0.5,chan,cat,2,lbs,1.0000
9,"Chan, Zog",dog,20 lbs,7,chan,dog,20,lbs,1.0000

## 8) Create a new column called `weight_lbs`, which calculates the pet's weight in lbs by multiplying `weight_quantity` by `unit_factor`

In [105]:
pets['weight_quantity'] = pets['weight_quantity'].astype(float)

pets['weight_lbs'] = pets['weight_quantity']*pets['unit_factor']
pets

,name,species,weight,years_old,last_name,animal_type,weight_quantity,weight_unit,unit_factor,weight_lbs
0,"smith, fido",dog,5 lbs,1,smith,dog,5.0,lbs,1.0000,5.0000
1,"SMITH,, Bella",CAT,7 lbs,10,smith,cat,7.0,lbs,1.0000,7.0000
2,"Ortiz, Milo",dog,15 lbs,5,ortiz,dog,15.0,lbs,1.0000,15.0000
3,"Smith, Goldie",goldfish,7 oz,???,smith,goldfish,7.0,oz,0.0625,0.4375
4,"Kim, Fuzz",cat,3 lbs,5 (five),kim,cat,3.0,lbs,1.0000,3.0000
5,"Jones, Las Vegas",DOG,12 lbs,unknown,jones,dog,12.0,lbs,1.0000,12.0000
6,Jones; fifi,puppy,2 lbs,0.25,jones,dog,2.0,lbs,1.0000,2.0000
7,"Lee, nemo",gold fish,10 oz,2,lee,goldfish,10.0,oz,0.0625,0.6250
8,"Chan, ZIGGY",kitten,2 lbs,0.5,chan,cat,2.0,lbs,1.0000,2.0000
9,"Chan, Zog",dog,20 lbs,7,chan,dog,20.0,lbs,1.0000,20.0000

## 9) What is the total weight of the pets?

In [126]:
pets['weight_lbs'].sum()

67.0625

## 10)  And which family's pets weigh the most, total?

In [124]:
pets.groupby('last_name')['weight_lbs'].sum()

last_name
chan     22.0000
jones    14.0000
kim       3.0000
lee       0.6250
ortiz    15.0000
smith    12.4375
Name: weight_lbs, dtype: float64

## 11) Of the known ages, what's the average pet age?

(You should get `3.84375`; if not, make sure you're accounting for numbers like `0.5` correctly.)

In [180]:
import re

# pets['age'] = pets['years_old'].str.extract(r'(\d+|0(?:\.\d+)?)').astype(float)
pets['age'] = pets['years_old'].str.extract(r'(0\.\d*|\d*)')
pets['age'] = pets['age'].replace("","0")
pets['age'] = pets['age'].astype(float)
pets

,name,species,weight,years_old,last_name,animal_type,weight_quantity,weight_unit,unit_factor,weight_lbs,age
0,"smith, fido",dog,5 lbs,1,smith,dog,5.0,lbs,1.0000,5.0000,1.00
1,"SMITH,, Bella",CAT,7 lbs,10,smith,cat,7.0,lbs,1.0000,7.0000,10.00
2,"Ortiz, Milo",dog,15 lbs,5,ortiz,dog,15.0,lbs,1.0000,15.0000,5.00
3,"Smith, Goldie",goldfish,7 oz,???,smith,goldfish,7.0,oz,0.0625,0.4375,0.00
4,"Kim, Fuzz",cat,3 lbs,5 (five),kim,cat,3.0,lbs,1.0000,3.0000,5.00
5,"Jones, Las Vegas",DOG,12 lbs,unknown,jones,dog,12.0,lbs,1.0000,12.0000,0.00
6,Jones; fifi,puppy,2 lbs,0.25,jones,dog,2.0,lbs,1.0000,2.0000,0.25
7,"Lee, nemo",gold fish,10 oz,2,lee,goldfish,10.0,oz,0.0625,0.6250,2.00
8,"Chan, ZIGGY",kitten,2 lbs,0.5,chan,cat,2.0,lbs,1.0000,2.0000,0.50
9,"Chan, Zog",dog,20 lbs,7,chan,dog,20.0,lbs,1.0000,20.0000,7.00

In [183]:
pets['age'].mean()

3.075

---

---

---